######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 26 17:31:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tabmainwindow.h tabpreviewpopup.h tabwidget.h
SOURCES += main.cpp tabmainwindow.cpp tabpreviewpopup.cpp tabwidget.cpp
